### ISSUE TITLE
En liten undring

### ISSUE THREAD

**Issue by lipadeus** [fuffenz/ha-sensor-sl#4]
Funkar inte denna sensor med allt som är från trafiklab så som ULs trafik också? Är det kanske inte stödjer just GTFS utan bara SL liner.

Annars kanske jag tar och bygger en UL sensor baserad på din kod om det går för sig? 

Annars verkar detta funka hur fint som helst.

**Comment by fuffenz** [comment]
Jag har inte kollat på UL så jag vågar inte svara på vad det kan vara för skillnader, men givetvis är det bara att använda kod om du har nytta av den!
